- backend/package-lock.json
- backend/package.json
- backend/src/utils/logger.ts
Added a module which exports a function that creates a logger for a given module.
Its formats the log and transports it to log files and the console
> Create a general logger

- backend/.eslintrc
- backend/src/models/user.model.ts
ESlint recommends that we use `type` instead of `Interface`
> Change User model interface to type

- backend/src/controllers/auth.controller.ts
- backend/src/models/user.model.ts
- backend/src/utils/validator.ts
Updated the `IUser` interface
Created a minimized type of `IUser` called `IUserDetails` and implemented a function which converts `IUser` to `IUserDetails`
Updated the JWT to sign the entire User Details
> 21 save whole user details in jwt

- backend/package-lock.json
- backend/package.json
- backend/src/controllers/auth.controller.ts
- backend/src/models/user.model.ts
- shared-types/index.d.ts
> feat(types): export user types

- backend/src/db.ts
> change log level to error on db command failed

- backend/src/controllers/user.controller.ts
- backend/src/tests/user.test.ts
- backend/src/utils/logger.ts
Updated the User Controller and added tests.
> 57 limit access on personal user endpoints

- backend/src/app.ts
- backend/src/tests/file.test.ts
> Add public file serving. implemented tests

- backend/package-lock.json
- backend/src/controllers/experience.controller.ts
- backend/src/controllers/user.controller.ts
- backend/src/routes/experience.route.ts
- backend/src/tests/experience.test.ts
- shared-types/index.d.ts
> feat(tests): implement tests

- backend/src/app.ts
- backend/src/db.ts
- frontend/src/main.tsx
- frontend/src/pages/auth/login/index.tsx
- frontend/src/pages/auth/register/index.tsx
- frontend/src/pages/profile/index.tsx
- frontend/src/services/auth-service.ts
> 54 implement loader for login and register

- backend/src/controllers/experience.controller.ts
- backend/src/routes/experience.route.ts
- backend/src/tests/experience.test.ts
- frontend/src/pages/experiences/components/experience-card.scss
- frontend/src/pages/experiences/components/experience-card.tsx
- frontend/src/pages/experiences/components/experiences-list.tsx
- frontend/src/services/experience-service.ts
> 84 delete experience

- backend/src/controllers/movie.controller.ts
- backend/src/routes/movie.route.ts
- backend/src/tests/movie.test.ts
- frontend/src/services/movie-service.ts
> 47 search movies by string route

- backend/src/controllers/experience.controller.ts
- backend/src/tests/experience.test.ts
- frontend/src/pages/experiences/components/experiences-list.tsx
- frontend/src/pages/experiences/index.tsx
- frontend/src/pages/experiences/new-experience-dialog/index.tsx
- frontend/src/services/experience-service.ts
- frontend/vite.config.ts
> feat(experiences): show only my experiences

- frontend/src/pages/experiences/comments/index.tsx
> feat(comments): update comments

- backend/src/app.ts
- frontend/src/helpers/auth.context.tsx
- frontend/src/pages/experiences/components/experience-card.tsx
- frontend/src/services/api-client.ts
> fix(bugs): fix bugs

- backend/src/routes/experience.route.ts
- backend/src/routes/movie.route.ts
- backend/src/routes/user.route.ts
> fix swagger routes

- frontend/src/pages/experiences/experience-dialog/components/experience-dialog.tsx
> fix(edit): fix unallowed user access

- frontend/src/pages/experiences/index.tsx
- tgmuctl.sh
> 104 add error handing in tgmuctl

- backend/src/controllers/experience.controller.ts
- backend/src/controllers/user.controller.ts
- frontend/src/pages/experiences/components/experience-card.tsx
- frontend/src/pages/experiences/experience-dialog/components/image-editor.tsx
> add '/' prefix to images in backend and remove prefix in frontend

- android/app/build.gradle.kts
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/tgmu/tgmu/data/local/MovieEntity.kt
- android/app/src/main/java/com/tgmu/tgmu/data/mapper/MovieExtensionFunctions.kt
- android/app/src/main/java/com/tgmu/tgmu/data/remote/BearerAuthInterceptor.kt
- android/app/src/main/java/com/tgmu/tgmu/data/remote/TmdbApi.kt
- android/app/src/main/java/com/tgmu/tgmu/data/remote/TmdbMovie.kt
- android/app/src/main/java/com/tgmu/tgmu/data/remote/TmdbMovieList.kt
- android/app/src/main/java/com/tgmu/tgmu/data/repository/MovieRepositoryImpl.kt
- android/app/src/main/java/com/tgmu/tgmu/di/MovieModule.kt
- android/app/src/main/java/com/tgmu/tgmu/domain/model/Movie.kt
- android/app/src/main/java/com/tgmu/tgmu/domain/repository/MovieRepository.kt
- android/app/src/main/java/com/tgmu/tgmu/ui/MainActivity.kt
- android/app/src/main/java/com/tgmu/tgmu/ui/TgmuApplication.kt
- android/app/src/main/java/com/tgmu/tgmu/ui/viewmodel/MoviesViewModel.kt
- android/app/src/main/res/layout/activity_main.xml
- android/build.gradle.kts
- android/gradle/libs.versions.toml
- backend/src/db.ts
> 110 setup directory structure and di

- android/app/build.gradle.kts
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/tgmu/tgmu/data/mapper/UserDetailsExtensionFunctions.kt
- android/app/src/main/java/com/tgmu/tgmu/data/remote/FirestoreUserDetails.kt
- android/app/src/main/java/com/tgmu/tgmu/data/repository/MovieRepositoryImpl.kt
- android/app/src/main/java/com/tgmu/tgmu/data/repository/UserDetailsRepositoryImpl.kt
- android/app/src/main/java/com/tgmu/tgmu/di/UserDetailsModule.kt
- android/app/src/main/java/com/tgmu/tgmu/domain/model/UserDetails.kt
- android/app/src/main/java/com/tgmu/tgmu/domain/repository/MovieRepository.kt
- android/app/src/main/java/com/tgmu/tgmu/domain/repository/UserDetailsRepository.kt
- android/app/src/main/java/com/tgmu/tgmu/ui/TgmuApplication.kt
- android/app/src/main/java/com/tgmu/tgmu/ui/activities/LoginActivity.kt
- android/app/src/main/java/com/tgmu/tgmu/ui/activities/RegisterActivity.kt
- android/app/src/main/java/com/tgmu/tgmu/ui/fragment/DiscoverFragment.kt
- android/app/src/main/java/com/tgmu/tgmu/ui/fragment/ProfileFragment.kt
- android/app/src/main/java/com/tgmu/tgmu/ui/viewmodel/MoviesViewModel.kt
- android/app/src/main/java/com/tgmu/tgmu/ui/viewmodel/UsersDetailsViewModel.kt
- android/app/src/main/java/com/tgmu/tgmu/utils/Resource.kt
- android/app/src/main/res/drawable/ic_back.xml
- android/app/src/main/res/drawable/ic_today.xml
- android/app/src/main/res/layout/activity_register.xml
- android/app/src/main/res/layout/fragment_discover.xml
- android/app/src/main/res/layout/loading_modal.xml
- android/app/src/main/res/values/strings.xml
- android/gradle/libs.versions.toml
> Register screen and user details

- android/app/build.gradle.kts
- android/app/src/main/java/com/tgmu/tgmu/data/repository/UserDetailsRepositoryImpl.kt
- android/app/src/main/java/com/tgmu/tgmu/domain/model/UpdateUserDetailsForm.kt
- android/app/src/main/java/com/tgmu/tgmu/domain/repository/UserDetailsRepository.kt
- android/app/src/main/java/com/tgmu/tgmu/ui/TgmuApplication.kt
- android/app/src/main/java/com/tgmu/tgmu/ui/fragment/ProfileFragment.kt
- android/app/src/main/java/com/tgmu/tgmu/ui/viewmodel/UsersDetailsViewModel.kt
- android/app/src/main/java/com/tgmu/tgmu/utils/PreferencesHelper.kt
- android/app/src/main/res/drawable/ic_close.xml
- android/app/src/main/res/layout/dialog_edit_profile.xml
- android/app/src/main/res/layout/fragment_profile.xml
- android/app/src/main/res/values/strings.xml
- android/app/src/main/res/values/styles.xml
- android/gradle/libs.versions.toml
> Profile screen
